### ISSUE TITLE
help for setup and improve suggested defaults

### ISSUE THREAD

**Issue by matu3ba** [nvimdev/dyninput.nvim#1]
Often lsps provide such changes as functionality one needs to jump to.
Thus it would be nice to have an overview for languages what to use to refactor code.

1. Would you be open to add a table in the README of 1. common refactorings for word delimiter symbols and 2. if another tool exists ?
2. Or where should a user look for these?
3. typo in description: s/accroding rules and filter/according to rules and filter.

**Comment by glepnir** [comment]
I don't know what do you mean
